apiVersion: v1
kind: Secret
metadata:
  name: application-secret
type: Opaque
data:
  REDIS_PASSWORD: cmRzaGFyZFBhc3MxMjM=
  DB_PASSWORD: c3FsaGFyZFBhc3MxMjM=
  APP_KEY: YmFzZTY0Om9LaGhJSVVlQ3BBQzh3THBNaFVsM0xiamRqb3NxL0VJNDJTdmFadGNhY1U9
