---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: financials-tracker-secret
  namespace: financials-tracker
spec:
  encryptedData:
    APP_KEY: AgBH0vfx0sWEP+G6zpDepXEFhI52qq5kOhVhDCvp0Yv47AH4gyfZZvD49f/T4md0UQWr259KB7svRH5oT+dW25h62CfPLW41OtqK1aUFxDVrJCxeHIL7oIB3eqE4U7YZ5WqkF3k+dQWtXaNA6GF396jrslolHezjaIGeoVmwcWsp/eRDFFxVCC+rtCwW21vSrJ74f2QnP9IIGla+UtlXigaFihaUzNFyZrgRpnvsdtRTLtn81lGlSjtshL/WWj6Ay8Q5c0G3++syTYGu01NIRbUWE0Phrgf5eSbzlZV90Uguuqn830UBABJJY9IUsiA6LCFue6I0gzSDfM40Lzi7EG8jnKhKC/ND7Mu4z9icNqC3Vm2uampPJJhfi3PxJqsBDrxN14dbjQO1VVH/kWNFLZh+Dd79RLpMskihRJv0pS8u4N3I5CzHNJ5y4eGM01uoRdnOyfMbL51hhVlGM41mr9aQReaCaI4dMUR9gf6nD1pmqsIWpdQ9sx/6LJlKTlaVs+148bW7yQoZo7q5nAwbrgBdBKeliD8xBvv6kbdQVqMLed1JL7kW/t9odjHZG7t9cRT3BHRZ4rPMn/FoHVnu3a5Ji3ur1zFv+myov0vs0fHoqYLqRyKQFwuZPGyUwjn5IH0HZA+ngLfy3JgGn0e/B6oihy5ALBNmYerryEZixAnLxn1SXNPFmGfwQmCz9vmXE0TQzxa5MLKV+0dsmrPSQb4McttNx/GXLgXYLoGftQKcWhP2LxPc3HcpHzeENGTV8bJFu24=
    DB_PASSWORD: AgB8E+mFIn1BPLVw3qlggeusmHDDtGgWE1fIAU+1Ewilm4z+RrjCs5SBJrnjjRV00zD7VkX07dhRH2C6IBCIk/JYjNkbIeID8OJ7Qwhi2lYZcyO9Dr5l8EkV56untFWJP3kw1Du4TlF+R/iTZyQzlNhqzmcAuv+L+r9shV2e1AenyySMePY4uUEZ0EEK0kIW85bHIu1nCZ6LEE1Ci7KCNqJY27erMmKNzULbcD/+YuVCvZkzJB6lg0OQ6UpzR6DGdFWsChoQIcZTToPWRbPrIjmyMdXLpLgzwyMJFxnTQoPR6FqJMii02YarJTTH1Qzbi/9pwfg+JoVkFJYy9xblkaYeugoR29w3wtFtBWg8wTO+hOEa8pe4NP4r0Kzew0Sv7E6RXbL1otXl579ym9qGjRSAdEOk6CX9KpT3oBPYvoyOLVpZE0u8xQEsI8vO/UPidRTSFhZgAQUH+2Ni2cixRSnxdRB05pe3ORmRNdtRv/ZTL2mO/oOWrYnVLOAgIbT6sYq/ZTD1oStl1YhTRJY82FR+Y8LzaVTpjKcusEQ6J1n7adQkYgEQ6js6dk8cGDDxEzfq7GldLk80S9z2gfSU1W307/2CQmMuOgx3vESlRkjSykNGxREUyb+UivVxZEwkzLzT7t91wmlKfL53u+zIktpWMbasTzgdwKBS903Nz90ix9FFzH/gpAQ2HLb9JTXpIfCE3cRIeTF9dLC7RXioCxomI3K+uw==
  template:
    metadata:
      name: financials-tracker-secret
      namespace: financials-tracker
    type: Opaque
