apiVersion: v1
kind: ConfigMap
metadata:
  name: financials-tracker-config
  namespace: financials-tracker
data:
  APP_NAME: Trade-Republic-Investment-Tracker
  APP_KEY: base64:CefspM+mDkJfZ2YFWf+cvC5htsMaxWKVXfuBHLWT1Go=
  APP_ENV: production
  APP_DEBUG: "false"
  APP_URL: https://financials-tracker.manuelpuchner.duckdns.org
  LOG_CHANNEL: stack
  LOG_LEVEL: debug
  DB_CONNECTION: pgsql
  DB_HOST: postgres.postgres.svc.cluster.local
  DB_PORT: "5432"
  DB_DATABASE: financials-tracker
  DB_USERNAME: financials_tracker_user
  BROADCAST_DRIVER: log
  CACHE_DRIVER: redis
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: redis
  SESSION_LIFETIME: "120"
  PROMETHEUS_NAMESPACE: default
  PROMETHEUS_METRICS_ROUTE_ENABLED: "true"
  PROMETHEUS_METRICS_ROUTE_PATH: metrics
  PROMETHEUS_METRICS_ROUTE_MIDDLEWARE: "null"
  PROMETHEUS_STORAGE_ADAPTER: memory
  REDIS_HOST: redis.redis.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_CLIENT: "predis"
  PROMETHEUS_REDIS_PREFIX: PROMETHEUS_
