apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: financials-tracker
data:
  default.conf: |
    default.conf: |
    server {
        listen  80 default_server;
        listen [::]:80 default_server;

        root /var/www/html/public;

        index index.php;
        error_page 404 index.php;

        location / {
            try_files $uri $uri/ /index.php;
        }

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param SCRIPT_NAME $fastcgi_script_name;
            fastcgi_param X-Forwarded-Proto $http_x_forwarded_proto;
        }
    }
