apiVersion: v1
kind: Service
metadata:
  labels:
    app: financials-tracker
  name: financials-tracker-service
  namespace: financials-tracker
spec:
  type: ClusterIP
  selector:
    app: financials-tracker
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
