---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: financials-tracker-secret
  namespace: financials-tracker
spec:
  encryptedData:
    DB_PASSWORD: AgB8E+mFIn1BPLVw3qlggeusmHDDtGgWE1fIAU+1Ewilm4z+RrjCs5SBJrnjjRV00zD7VkX07dhRH2C6IBCIk/JYjNkbIeID8OJ7Qwhi2lYZcyO9Dr5l8EkV56untFWJP3kw1Du4TlF+R/iTZyQzlNhqzmcAuv+L+r9shV2e1AenyySMePY4uUEZ0EEK0kIW85bHIu1nCZ6LEE1Ci7KCNqJY27erMmKNzULbcD/+YuVCvZkzJB6lg0OQ6UpzR6DGdFWsChoQIcZTToPWRbPrIjmyMdXLpLgzwyMJFxnTQoPR6FqJMii02YarJTTH1Qzbi/9pwfg+JoVkFJYy9xblkaYeugoR29w3wtFtBWg8wTO+hOEa8pe4NP4r0Kzew0Sv7E6RXbL1otXl579ym9qGjRSAdEOk6CX9KpT3oBPYvoyOLVpZE0u8xQEsI8vO/UPidRTSFhZgAQUH+2Ni2cixRSnxdRB05pe3ORmRNdtRv/ZTL2mO/oOWrYnVLOAgIbT6sYq/ZTD1oStl1YhTRJY82FR+Y8LzaVTpjKcusEQ6J1n7adQkYgEQ6js6dk8cGDDxEzfq7GldLk80S9z2gfSU1W307/2CQmMuOgx3vESlRkjSykNGxREUyb+UivVxZEwkzLzT7t91wmlKfL53u+zIktpWMbasTzgdwKBS903Nz90ix9FFzH/gpAQ2HLb9JTXpIfCE3cRIeTF9dLC7RXioCxomI3K+uw==
  template:
    metadata:
      name: financials-tracker-secret
      namespace: financials-tracker
    type: Opaque
