apiVersion: apps/v1
kind: Deployment
metadata:
  name: financials-tracker-deployment
  namespace: financials-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financials-tracker
  template:
    metadata:
      labels:
        app: financials-tracker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "80"
    spec:
      volumes:
        - name: logs
          emptyDir: {}
        - name: views
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: sessions
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-config
      securityContext:
        fsGroup: 82
      initContainers:
        - name: database-migrations
          image: ghcr.io/manuelpuchner/trade-republic-investment-tracker/fpm:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: financials-tracker-config
            - secretRef:
                name: financials-tracker-secret
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/storage/logs
            - name: views
              mountPath: /var/www/html/storage/framework/views
            - name: cache
              mountPath: /var/www/html/storage/framework/cache
            - name: sessions
              mountPath: /var/www/html/storage/framework/sessions
          command:
            - "sh"
            - "-c"
          args:
            - |
              mkdir -p /var/www/html/storage/framework/views
              mkdir -p /var/www/html/storage/framework/cache
              mkdir -p /var/www/html/storage/framework/sessions
              mkdir -p /var/www/html/storage/logs
              chown -R www-data:www-data /var/www/html/storage
              php artisan migrate --force
      containers:
        - name: nginx
          imagePullPolicy: IfNotPresent
          image: ghcr.io/manuelpuchner/trade-republic-investment-tracker/nginx:latest
          resources:
            {}
            # limits:
            #   cpu: 500m
            #   memory: 50M
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
        - name: fpm
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: financials-tracker-config
            - secretRef:
                name: financials-tracker-secret
          securityContext:
            runAsUser: 82
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/storage/logs
            - name: views
              mountPath: /var/www/html/storage/framework/views
            - name: cache
              mountPath: /var/www/html/storage/framework/cache
            - name: sessions
              mountPath: /var/www/html/storage/framework/sessions
          resources: {}
          image: ghcr.io/manuelpuchner/trade-republic-investment-tracker/fpm:latest
          ports:
            - containerPort: 9000
