apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: financials-tracker-ingress
  namespace: financials-tracker
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`financials-tracker.manuelpuchner.duckdns.org`)
      kind: Rule
      services:
        - name: financials-tracker-service
          port: 80
  tls:
    secretName: financials-tracker-tls
