apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: financials-tracker-sealed-secret
  namespace: financials-tracker
spec:
  encryptedData:
    DB_PASSWORD: AgC5aLWf1EkD84e2L0RucSBXlYNJsHwICFz1dAwWM0D2PQQtJIvpuhHx9cNj4QTTBk8NIG9RKRLB+V40EsqD94T3E1i+jhT3PoP+kJHbWdILOfHyALDMOCxFF6BqbADB8uyTBHcFBKEK524ebKVjfwRBovyiGfkLfZI4Au2euujxw4r7bjT6NdOPloaX+6+9jgAr1e3YSpC8MlhjLYvwIsJETiCzY+rpBNWIgqJ0uDqKcUcnI+Rz1ST96Zy6kBEJRrRR2P8B75q/QqctokAIAnRhCwgJ4r20/8XoGXsSDzIqTyhhCIs+rsUCzg26SQgLLUmMqXWvHnOl0N41rzc1qiXXW66gHYrimaW3ZWXeMwKyhFX07RrcMu6erwICpgY7TPAcVfUC1kOyxPfFCMRr6+2GIuHZs7MLqpPz9qRHFq5nJIiFLjTwFwS/zQ82Bcgl0HerccX2gXcXxCx7HSzIAxeuK9XXKkim7kwyQ+vejWyyBmEHvgk0LQBxBSdlI8xyw4ffhCtlCNXepXeA8TNjhQmd+Dd/KuD+o8OIrNeiJpFI7Z1Gvwg5XUX9emAWOw/rhB3kGAwmxA1EDbmIACha/p6WHwGGqbr7+v1UUcmr7BwGkOe7I0so2pggWmEA0qr7VDygFlk43Wl3kqggiiKwd55omcqlJnokrGkcfhcEC7/yB/v8DpQEOJRsJGGK7pf2JcOcT57fUemxE20nyX7AO6cnPNpquYIHbyc6EdnR
  template:
    metadata:
      name: financials-tracker-secret
    type: Opaque
