apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trade-republic-tracker
  namespace: argocd
  annotations:
    # ArgoCD Image Updater - überwacht automatisch neue Container-Images
    argocd-image-updater.argoproj.io/image-list: app=ghcr.io/dein-github-user/trade-republic-tracker # ANPASSEN!
    argocd-image-updater.argoproj.io/app.update-strategy: latest
    argocd-image-updater.argoproj.io/app.allow-tags: regexp:^main-.*$
    argocd-image-updater.argoproj.io/write-back-method: argocd
  # Finalizer für automatisches Cleanup
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    # Git Repository
    repoURL: https://github.com/ManuelPuchner/trade-republic-tracker.git # ANPASSEN!
    targetRevision: main # oder master, production, etc.
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: trade-republic-tracker

  syncPolicy:
    automated:
      prune: true # Automatisches Löschen von Ressourcen
      selfHeal: true # Automatisches Korrigieren von Drift
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true # Namespace automatisch erstellen
      - PruneLast=true # Zuerst neue Ressourcen, dann alte löschen
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health Check Konfiguration
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
