apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: trade-republic-tracker
  namespace: trade-republic-tracker
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`finanz-verwaltung.home.lab`)
      services:
        - name: trade-republic-tracker
          port: 80
  tls: {}
